name: wheezy
on: push

jobs:
  build-wheezy-slim:
    name: wheezy-slim
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.0.0
      - name: make build-wheezy-slim
        run: make build-wheezy-slim
      - name: make docker-login
        run: |
          make docker-login \
          DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }} \
          DOCKERHUB_PASSWORD=${{ secrets.DOCKERHUB_PASSWORD }}
      - name: make push-wheezy-slim
        run: make push-wheezy-slim
